### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by pfetsch** [lgottwald/PaPILO#30] opened 2020-07-20 16:29 UTC
I get
```
lib/include/papilo/external/tbb/include/tbb/task.h:1125:28: runtime error: member call on address 0x7efc1904b200 which does not point to an object of type 'scheduler'
0x7efc1904b200: note: object is of type 'tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>'
 00 00 00 00  b0 aa 75 1b fc 7e 00 00  00 00 00 00 00 00 00 00  60 7f 05 19 fc 7e 00 00  60 7f 05 19
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>'
lib/include/papilo/external/tbb/include/tbb/task.h:801:37: runtime error: member call on address 0x7efc1904b200 which does not point to an object of type 'scheduler'
0x7efc1904b200: note: object is of type 'tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>'
 00 00 00 00  b0 aa 75 1b fc 7e 00 00  00 00 00 00 00 00 00 00  60 7f 05 19 fc 7e 00 00  60 7f 05 19
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>'
lib/include/papilo/external/tbb/include/tbb/task.h:809:49: runtime error: member call on address 0x7efc1904b200 which does not point to an object of type 'scheduler'
0x7efc1904b200: note: object is of type 'tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>'
 00 00 00 00  b0 aa 75 1b fc 7e 00 00  00 00 00 00 00 00 00 00  60 7f 05 19 fc 7e 00 00  60 7f 05 19
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>'
```

How to reproduce: use v70-bugfix, ug current master (dc15357):
```
SCIP version 7.0.2 [precision: 8 byte] [memory: block] [mode: debug] [LP solver: CPLEX 12.9.0.0] [GitHash: 4dc89d4]
Copyright (C) 2002-2020 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)
External codes: 
  Readline 6.3         GNU library for command line editing (gnu.org/s/readline)
  CPLEX 12.9.0.0       Linear Programming Solver developed by IBM (www.cplex.com)
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (www.coin-or.org/CppAD)
  ZLIB 1.2.8           General purpose compression library by J. Gailly and M. Adler (zlib.net)
  GMP 6.1.0            GNU Multiple Precision Arithmetic Library developed by T. Granlund (gmplib.org)
  PaPILO 1.0.0.1       parallel presolve for integer and linear optimization (https://github.com/lgottwald/PaPILO)
```
Then run
```
fscip-1.0.0.linux.x86_64.gnu.dbg.cpx default-debug7.prm neos859080.mps.gz -s default-debug7.set
```

**Comment by pfetsch** [comment] 2020-07-28 18:02
I think the output also arises when running ordinary SCIP with Papilo in the debugger ...

**Comment by lgottwald** [comment] 2020-07-29 07:38
This output comes from one of the sanitizers and is caused by tbb. It may go away with future versions but also seems to be a false positive. It would be good to not enable the sanitizers that cause this message by default in the Makefile. From the papilo code there is not really something that can be done about it.

**Comment by lgottwald** [comment] 2020-07-29 07:39
See here: https://github.com/oneapi-src/oneTBB/issues/140

**Comment by ambros-gleixner** [comment] 2020-09-18 08:57
@lgottwald In which Makefile / cmake of which projects does the -fsanitize need to be deactivated? In PaPILO / SCIP / FiberSCIP?

**Comment by lgottwald** [comment] 2020-09-18 09:36
In the SCIP makefiles where the sanitizer flags are always automatically added during debug compilation this occurs. In the cmake files one needs to use an extra flag for enabling the sanitizers and they are not always enabled in debug mode.

**Comment by lgottwald** [comment] 2020-10-02 14:39
This has been fixed in the SCIP makefiles now by avoiding to use the sanitizers for the PaPILO interface

**Closed as completed** 2020-10-02 14:39 UTC
